# Generated by Django 3.1 on 2020-08-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_completed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='time_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completion Time'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Time'),
        ),
    ]
